//Copyright 2015 Erik De Rijcke
//
//Licensed under the Apache License,Version2.0(the"License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing,software
//distributed under the License is distributed on an"AS IS"BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class examples_ShmPool */

#ifndef _Included_examples_ShmPool
#define _Included_examples_ShmPool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     examples_ShmPool
 * Method:    createTmpFileNative
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_examples_ShmPool_createTmpFileNative
  (JNIEnv *, jclass);

/*
 * Class:     examples_ShmPool
 * Method:    mapNative
 * Signature: (IJZZ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_examples_ShmPool_mapNative
  (JNIEnv *, jclass, jint, jlong, jboolean, jboolean);

/*
 * Class:     examples_ShmPool
 * Method:    unmapNative
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_examples_ShmPool_unmapNative
  (JNIEnv *, jclass, jobject);

/*
 * Class:     examples_ShmPool
 * Method:    truncateNative
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_examples_ShmPool_truncateNative
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     examples_ShmPool
 * Method:    closeNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_examples_ShmPool_closeNative
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
