/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_freedesktop_wayland_client_egl_WlEglJNI */

#ifndef _Included_org_freedesktop_wayland_client_egl_WlEglJNI
#define _Included_org_freedesktop_wayland_client_egl_WlEglJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_freedesktop_wayland_client_egl_WlEglJNI
 * Method:    createEglWindow
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_org_freedesktop_wayland_client_egl_WlEglJNI_createEglWindow
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_freedesktop_wayland_client_egl_WlEglJNI
 * Method:    destroyEglWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_freedesktop_wayland_client_egl_WlEglJNI_destroyEglWindow
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_freedesktop_wayland_client_egl_WlEglJNI
 * Method:    resize
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_org_freedesktop_wayland_client_egl_WlEglJNI_resize
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_freedesktop_wayland_client_egl_WlEglJNI
 * Method:    getAttachedSize
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_org_freedesktop_wayland_client_egl_WlEglJNI_getAttachedSize
  (JNIEnv *, jclass, jlong, jintArray);

#ifdef __cplusplus
}
#endif
#endif
